//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasinoTable
    {
        public int RoundID { get; set; }
        public int Pot { get; set; }
        public int Bet { get; set; }
        public string Reel1Symbol { get; set; }
        public string Reel2Symbol { get; set; }
        public string Reel3Symbol { get; set; }
        public string Status { get; set; }
    }
}
